### ISSUE TITLE
implement notify server

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/pixelfed_ynh#275]
https://github.com/pixelfed/notify

**Comment by lapineige** [comment]
If anyone have some time to try to implement this, contributions are welcomed :)

**Comment by jothgard** [comment]
Push Notification support has officially been merged, so hopefully it only needs to update from the master repo?

link: https://github.com/pixelfed/pixelfed/pull/5303

Would be amazing to see this be on the yunohost app!

**Comment by lapineige** [comment]
I guess there will be at least some configuration option to tweak, and maybe Nginx config too ?

**Comment by jothgard** [comment]
> I guess there will be at least some configuration option to tweak, and maybe Nginx config too ?

Have no coding skills at all, so I dont know, just hope to see yunohost app support for notifications.

**Comment by jothgard** [comment]
Any news?

**Comment by lapineige** [comment]
I didn't have time to take a look.

**Comment by jothgard** [comment]
> I didn't have time to take a look.

I see, thanks for the reply, if you have time, i thing you only need to update the YunoHost app to the latest Pixelfed Version, the notification should be merger in that one.

**Comment by lapineige** [comment]
Then #277 should fix it.

**Comment by jothgard** [comment]
> Then #277 should fix it.

Will try it out when i can update the yunohost app :) Thanks!!

**Comment by jothgard** [comment]
I did upgrade, seems that yunohost app has support for notifications, can enable it on server and on the IOS pixelfed app, but do not get any notifications, don't know if it is problem with the API key i got, or if it is yunohost app.

**Comment by jothgard** [comment]
Hello, seems that i still do not get any notifications on IOS or Android client, have enabled Pusch notifications on server side without any issue/error, and same on the mobile clients side, no error when enable notifications, but still don't get any notifications at all.
